"""Shared, file-backed conversation store + explicit state machine (human-in-the-loop backend).

This is the Streamlit-idiomatic stand-in for a backend service. There is no HTTP API (a deliberate
take-home design choice — see README §14); instead the customer console and the human-support
dashboard both read/write the SAME on-disk store, so an escalation raised in one browser session is
visible to a human agent in another. One JSON file per conversation
(``data/conversations/<id>.json``) is written atomically (temp file + ``os.replace``) so a reader
never observes a half-written file.

Concurrency (honest limitation): writes are guarded by an in-process lock and each save is atomic,
so the realistic single-customer / single-agent-per-conversation pattern is safe. Two processes
mutating the *same* conversation simultaneously is last-writer-wins on that file — acceptable for a
prototype, documented, not claimed otherwise.

State machine (guarded — invalid transitions raise ``InvalidTransition``):

    AI_ACTIVE ──escalate──▶ WAITING_FOR_HUMAN ──human replies──▶ HUMAN_ACTIVE ──resolve──▶ RESOLVED
        │                        │                                                            │
        └──────── resolve ───────┴──────────────── resolve ──────────────────────────────────┤
                                                                                      reopen ◀─┘
    RESOLVED ──close──▶ CLOSED ;  a new customer message on a RESOLVED/CLOSED convo reopens it.
"""
from __future__ import annotations

import json
import os
import threading
import uuid
from datetime import datetime, timezone

from . import config

# ---- states ----
AI_ACTIVE = "AI_ACTIVE"
WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
HUMAN_ACTIVE = "HUMAN_ACTIVE"
RESOLVED = "RESOLVED"
CLOSED = "CLOSED"

STATES = {AI_ACTIVE, WAITING_FOR_HUMAN, HUMAN_ACTIVE, RESOLVED, CLOSED}

# allowed transitions (same->same is always allowed as a no-op and not listed here)
_ALLOWED = {
    AI_ACTIVE: {WAITING_FOR_HUMAN, RESOLVED, CLOSED},
    WAITING_FOR_HUMAN: {HUMAN_ACTIVE, RESOLVED, CLOSED},
    HUMAN_ACTIVE: {WAITING_FOR_HUMAN, RESOLVED, CLOSED},
    RESOLVED: {HUMAN_ACTIVE, WAITING_FOR_HUMAN, CLOSED},   # reopen or close
    CLOSED: {WAITING_FOR_HUMAN},                            # reopen only
}

# roles
CUSTOMER, AI, HUMAN, SYSTEM = "customer", "ai", "human", "system"

_LOCK = threading.RLock()


class InvalidTransition(Exception):
    """Raised when a status change is not permitted by the state machine."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


class ConversationStore:
    def __init__(self, root: str | None = None):
        self.root = root or config.CONVERSATIONS_DIR
        os.makedirs(self.root, exist_ok=True)

    # ---------- low-level io (atomic) ----------
    def _path(self, conversation_id: str) -> str:
        # conversation_id is generated by us (uuid hex + prefix); guard anyway against path escapes
        safe = os.path.basename(str(conversation_id))
        return os.path.join(self.root, f"{safe}.json")

    def _write(self, conv: dict) -> None:
        conv["updated_at"] = _now()
        path = self._path(conv["conversation_id"])
        tmp = f"{path}.{uuid.uuid4().hex[:6]}.tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(conv, f, ensure_ascii=False, indent=2)
        os.replace(tmp, path)   # atomic on the same filesystem

    # ---------- crud ----------
    def create_conversation(self, customer_id: str = "customer",
                            conversation_id: str | None = None) -> dict:
        with _LOCK:
            cid = conversation_id or _new_id("conv")
            conv = {
                "conversation_id": cid,
                "customer_id": customer_id,
                "status": AI_ACTIVE,
                "intent": "",
                "safety_status": "no",
                "escalation_reason": "",
                "created_at": _now(),
                "updated_at": _now(),
                "messages": [],
                "feedback": {},          # message_id -> {feedback, ts}
                "resolution": None,      # {text, category, note, human_agent, resolved_at, resolution_id}
                "retrieved_evidence": [],
            }
            self._write(conv)
            return conv

    def get(self, conversation_id: str) -> dict | None:
        path = self._path(conversation_id)
        if not os.path.exists(path):
            return None
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def list_conversations(self, status: str | None = None) -> list:
        out = []
        if not os.path.isdir(self.root):
            return out
        for name in os.listdir(self.root):
            if not name.endswith(".json"):
                continue
            try:
                with open(os.path.join(self.root, name), "r", encoding="utf-8") as f:
                    conv = json.load(f)
            except (json.JSONDecodeError, OSError):
                continue    # skip a file mid-write / corrupt; never crash the dashboard
            if status is None or conv.get("status") == status:
                out.append(conv)
        out.sort(key=lambda c: c.get("updated_at", ""), reverse=True)
        return out

    def counts_by_status(self) -> dict:
        counts = {s: 0 for s in STATES}
        for conv in self.list_conversations():
            counts[conv.get("status", AI_ACTIVE)] = counts.get(conv.get("status", AI_ACTIVE), 0) + 1
        return counts

    # ---------- messages ----------
    def add_message(self, conversation_id: str, role: str, text: str,
                    meta: dict | None = None, dedup: bool = False) -> dict | None:
        if role not in (CUSTOMER, AI, HUMAN, SYSTEM):
            raise ValueError(f"invalid role: {role!r}")
        with _LOCK:
            conv = self.get(conversation_id)
            if conv is None:
                raise KeyError(conversation_id)
            # a new customer message on a closed/resolved convo reopens it (never silently dropped)
            if role == CUSTOMER and conv["status"] in (RESOLVED, CLOSED):
                self._transition(conv, WAITING_FOR_HUMAN)
                conv["messages"].append(self._sys_msg("Conversation reopened by a new customer message."))
            if dedup and conv["messages"]:
                last = conv["messages"][-1]
                if last["role"] == role and last["text"] == text:
                    return None   # idempotent: identical consecutive message (double-submit) ignored
            msg = {"message_id": _new_id("msg"), "role": role, "text": text,
                   "ts": _now(), "meta": meta or {}}
            conv["messages"].append(msg)
            # a human's first reply moves a waiting conversation to HUMAN_ACTIVE
            if role == HUMAN and conv["status"] == WAITING_FOR_HUMAN:
                self._transition(conv, HUMAN_ACTIVE)
            self._write(conv)
            return msg

    def _sys_msg(self, text: str) -> dict:
        return {"message_id": _new_id("msg"), "role": SYSTEM, "text": text, "ts": _now(), "meta": {}}

    # ---------- feedback ----------
    def add_feedback(self, conversation_id: str, message_id: str, feedback: str) -> dict:
        """Idempotent per (message_id): re-clicking the same feedback is a no-op."""
        with _LOCK:
            conv = self.get(conversation_id)
            if conv is None:
                raise KeyError(conversation_id)
            existing = conv["feedback"].get(message_id)
            changed = not (existing and existing.get("feedback") == feedback)
            conv["feedback"][message_id] = {"feedback": feedback, "ts": _now()}
            if changed:
                self._write(conv)
            return {"conversation_id": conversation_id, "message_id": message_id,
                    "feedback": feedback, "changed": changed}

    # ---------- state machine ----------
    def _transition(self, conv: dict, new_status: str) -> None:
        cur = conv["status"]
        if new_status not in STATES:
            raise ValueError(f"unknown status: {new_status!r}")
        if new_status == cur:
            return
        if new_status not in _ALLOWED.get(cur, set()):
            raise InvalidTransition(f"{cur} -> {new_status} is not allowed")
        conv["status"] = new_status

    def set_status(self, conversation_id: str, new_status: str) -> dict:
        with _LOCK:
            conv = self.get(conversation_id)
            if conv is None:
                raise KeyError(conversation_id)
            self._transition(conv, new_status)
            self._write(conv)
            return conv

    def escalate(self, conversation_id: str, reason: str, intent: str | None = None,
                 safety_status: str | None = None, retrieved_evidence: list | None = None) -> dict:
        with _LOCK:
            conv = self.get(conversation_id)
            if conv is None:
                raise KeyError(conversation_id)
            if conv["status"] == WAITING_FOR_HUMAN:
                return conv   # already queued (idempotent)
            self._transition(conv, WAITING_FOR_HUMAN)
            conv["escalation_reason"] = reason
            if intent is not None:
                conv["intent"] = intent
            if safety_status is not None:
                conv["safety_status"] = safety_status
            if retrieved_evidence is not None:
                conv["retrieved_evidence"] = retrieved_evidence
            conv["messages"].append(self._sys_msg(f"Escalated to Human Support — {reason}"))
            self._write(conv)
            return conv

    def set_resolution(self, conversation_id: str, resolution: str, category: str = "",
                       note: str = "", human_agent: str = "human_agent",
                       resolution_id: str = "") -> dict:
        with _LOCK:
            conv = self.get(conversation_id)
            if conv is None:
                raise KeyError(conversation_id)
            self._transition(conv, RESOLVED)
            conv["resolution"] = {
                "text": resolution, "category": category, "note": note,
                "human_agent": human_agent, "resolved_at": _now(),
                "resolution_id": resolution_id,
            }
            conv["messages"].append(self._sys_msg("Conversation resolved by Human Support."))
            self._write(conv)
            return conv
